version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_FILE: /tmp/realms/keycloak-realm.json
    volumes:
      - ./docker/keycloak/realms/:/tmp/realms/
    ports:
      - "8080:8080"
    command:
      - start-dev

  rabbitmq:
    image: docker.io/bitnami/rabbitmq
    ports:
      - '4369:4369' # epmd
      - '5551:5551' # clustering
      - '5552:5552' # clustering
      - '5672:5672' # AMQP
      - '25672:25672' # Erlang distribution port
      - '15672:15672' # Web UI
      - '61613:61613' # STOMP
      - '61614:61614' # STOMP over TLS
      - '1883:1883' # MQTT
      - '8883:8883' # MQTT over TLS
      - '15675:15675' # MQTT over WebSockets
      - '15692:15692' # MQTT over WebSockets/SSL
    environment:
      #- RABBITMQ_USERNAME=guest
      #- RABBITMQ_PASSWORD=guest
      - RABBITMQ_LOGS=-
      #- RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_mqtt,rabbitmq_web_mqtt,rabbitmq_auth_backend_oauth2,rabbitmq_auth_backend_cache,rabbitmq_recent_history_exchange,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_web_mqtt_examples
      - RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_mqtt,rabbitmq_web_mqtt
    #volumes:
    #  - ./docker/rabbitmq/rabbitmq.config:/bitnami/rabbitmq/conf/rabbitmq.config